[0m15:16:07.877213 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7cd60009b680>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7cd601a14650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7cd5ff7d0620>]}


============================== 15:16:07.906131 | 385a1707-f7a2-4e07-86b7-f70e5f994f2d ==============================
[0m15:16:07.906131 [info ] [MainThread]: Running with dbt=1.10.2
[0m15:16:07.906500 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/aderaldo/.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt init', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m15:16:07.937485 [info ] [MainThread]: Creating dbt configuration folder at /home/aderaldo/.dbt
[0m15:20:43.518893 [debug] [MainThread]: Starter project path: /home/aderaldo/Estudos/Workshop_jd/1_local_setup/.venv/lib/python3.12/site-packages/dbt/include/starter_project
[0m15:20:43.521584 [info ] [MainThread]: 
Your new dbt project "jornada_dw" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m15:20:43.522086 [info ] [MainThread]: Setting up your profile.
[0m15:35:06.813604 [info ] [MainThread]: Profile jornada_dw written to /home/aderaldo/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m15:35:06.823824 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 1138.9828, "process_in_blocks": "5208", "process_kernel_time": 0.152919, "process_mem_max_rss": "123820", "process_out_blocks": "33768", "process_user_time": 2.079911}
[0m15:35:06.825128 [debug] [MainThread]: Command `dbt init` succeeded at 15:35:06.824884 after 1138.98 seconds
[0m15:35:06.825897 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7cd5ff720ad0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7cd5ff298a40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7cd5ff59f140>]}
[0m15:35:06.826685 [debug] [MainThread]: Flushing usage events
[0m15:35:07.396092 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m10:08:07.999947 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7614093615e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x761406bceba0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x76140878a360>]}


============================== 10:08:08.004868 | bcdcf3d8-2442-460a-850b-f387894d2f2b ==============================
[0m10:08:08.004868 [info ] [MainThread]: Running with dbt=1.10.2
[0m10:08:08.005465 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/home/aderaldo/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt deps', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m10:08:08.006123 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/aderaldo/Estudos/Workshop_jd/2_data_warehouse/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:08:08.007727 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_success": false, "command_wall_clock_time": 0.047078248, "process_in_blocks": "51184", "process_kernel_time": 0.097786, "process_mem_max_rss": "98996", "process_out_blocks": "16", "process_user_time": 0.937535}
[0m10:08:08.008288 [debug] [MainThread]: Command `dbt deps` failed at 10:08:08.008176 after 0.05 seconds
[0m10:08:08.008707 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x761406ca8a70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x76140663e390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x761406119790>]}
[0m10:08:08.009129 [debug] [MainThread]: Flushing usage events
[0m10:08:08.973412 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:11:12.483666 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x723d254a8800>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x723d256a8fb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x723d254a8fe0>]}


============================== 11:11:12.485912 | b546bddd-d3c3-49f0-8f36-1416f53e3c84 ==============================
[0m11:11:12.485912 [info ] [MainThread]: Running with dbt=1.10.2
[0m11:11:12.486267 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/aderaldo/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt build --exclude-resource-type seed', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m11:11:12.486621 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/aderaldo/Estudos/Workshop_jd/2_data_warehouse/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:11:12.487507 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": false, "command_wall_clock_time": 0.04225205, "process_in_blocks": "0", "process_kernel_time": 0.076727, "process_mem_max_rss": "99476", "process_out_blocks": "8", "process_user_time": 0.901801}
[0m11:11:12.487963 [debug] [MainThread]: Command `dbt build` failed at 11:11:12.487865 after 0.04 seconds
[0m11:11:12.488302 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x723d25096150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x723d289b3b90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x723d256a8fb0>]}
[0m11:11:12.488779 [debug] [MainThread]: Flushing usage events
[0m11:11:13.441349 [debug] [MainThread]: An error was encountered while trying to flush usage events
